In [1]:
%matplotlib widget
import matplotlib
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from Data_functions import getData

In [2]:
points, vectors = getData('../data/obj/Psyche Hanuš.obj')

In [3]:
faces = np.array([points['x'][vectors['x'][:]-1], points['y'][vectors['y'][:]-1], points['z'][vectors['z'][:]-1]])
faces

array([[ 0.01089952,  0.01089952,  0.01089952, ...,  0.01089952,
         0.01089952,  0.01089952],
       [ 0.09192698,  0.16675759,  0.09192698, ...,  0.09192698,
         0.02338535,  0.09192698],
       [ 0.28921975,  0.30182763,  0.31708891, ..., -0.28639761,
        -0.25953623, -0.24294086]])

In [4]:
df = pd.DataFrame(faces)
df

0         1         2         3         4         5         6    \
0  0.010900  0.010900  0.010900  0.010900  0.084555  0.109920  0.010900   
1  0.091927  0.166758  0.091927  0.018490  0.091927  0.166758  0.187157   
2  0.289220  0.301828  0.317089  0.310186  0.278352  0.310186  0.266319   

        7         8         9    ...       790       791       792       793  \
0  0.010900 -0.091102 -0.062990  ... -0.060627  0.010900  0.010900  0.010900   
1  0.235540  0.091927  0.199689  ... -0.005880 -0.005880 -0.041877 -0.003813   
2  0.269828  0.289220  0.288693  ... -0.245688 -0.259536 -0.216674 -0.214537   

        794       795       796       797       798       799  
0  0.082618  0.082618  0.010900  0.010900  0.010900  0.010900  
1 -0.003813  0.091927  0.170552  0.091927  0.023385  0.091927  
2 -0.242941 -0.229622 -0.261823 -0.286398 -0.259536 -0.242941  

[3 rows x 800 columns]

In [5]:
df.shape[1]

800

In [6]:
a_f = []
for i in range(1, df.shape[1]):
    a_f.append(np.cross(df[i-1],df[i]))
a_f

[array([-0.02048348, -0.00013742,  0.00081562]),
 array([ 0.02513088, -0.00016634, -0.00081562]),
 array([ 2.26515249e-02,  7.52356933e-05, -8.00428548e-04]),
 array([-0.02336778,  0.02319391, -0.00056146]),
 array([-0.01790275,  0.00436872,  0.00399554]),
 array([-0.01364265, -0.02589304,  0.01875475]),
 array([-1.22286257e-02, -3.82466448e-05,  5.27353321e-04]),
 array([ 0.04331825, -0.0277342 ,  0.02246006]),
 array([-0.03121528,  0.00808257, -0.01240156]),
 array([0.03245974, 0.00042576, 0.00678787]),
 array([ 0.02228321, -0.007296  ,  0.00702081]),
 array([0.00668221, 0.03013843, 0.00012507]),
 array([ 0.01399786, -0.00015478, -0.00050788]),
 array([-0.04496182,  0.03276221,  0.00676805]),
 array([ 0.03117324, -0.00729457, -0.00916297]),
 array([-0.03046261,  0.02359633,  0.00962529]),
 array([-0.02103885,  0.00149399,  0.01191287]),
 array([-0.00764669, -0.01344664,  0.01313626]),
 array([-0.00815876, -0.0025111 ,  0.00536648]),
 array([-0.0123962 , -0.02431196,  0.02549785]),
 a